### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by SegaSonic2** [UnMars/Prolific-Joiner#10]
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packa
ges\webdriver_manager\core\driver_cache.py", line 151, in get_cache_key_driver_versio
n
    return driver.get_driver_version_to_download()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packa
ges\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packa
ges\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    resp = self._http_client.get(url=latest_release_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packa
ges\webdriver_manager\core\http.py", line 36, in get
    self.validate_response(resp)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packa
ges\webdriver_manager\core\http.py", line 15, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.co
m/LATEST_RELEASE_5.2.3790

All I could salvage at the moment. It seems to be due to chrome drivers, and a dead link somewhere. I'm not really experienced with these things on my own, but could you look into this please?

**Comment by usdbrl** [comment]
Can you try update the wedriver_manager library, and check if you have the lastest version of this script, who changed one line?

The command to update the library:
`pip install webdriver_manager --upgrade`

I've tried something similar, but could work only for me. 
So if you could test if the updated version of webdriver_manager is the solution, would be nice.

**Comment by hedwig2** [comment]
Had the same issue, and this fixed it. Thank you so much!

**Comment by SegaSonic2** [comment]
Didn't work for me? Gives me the same error.

**Comment by usdbrl** [comment]
Seems like the new Chrome versions already have the ChromeDriver installed with it. Looks like they've changed how the driver works since version 115, that change is reason for multiple mismatches in a few scripts.

That said, I would kindly request to also update selenium:
`pip install selenium --upgrade`

**Comment by usdbrl** [comment]
Seems like the new Chrome versions already have the ChromeDriver installed with it. Looks like they've changed how the driver works since version 115, that change is reason for multiple mismatches in a few scripts.

That change made "webdriver_manager" and "selenium" need some modifications.

That said, I would kindly request to also update selenium:
`pip install selenium --upgrade`

**Comment by SegaSonic2** [comment]
> Seems like the new Chrome versions already have the ChromeDriver installed with it. Looks like they've changed how the driver works since version 115, that change is reason for multiple mismatches in a few scripts.
> 
> That change made "webdriver_manager" and "selenium" need some modifications.
> 
> That said, I would kindly request to also update selenium: `pip install selenium --upgrade`

Did this, yet for some reason it refuses to work still. I've even reinstalled Python on my desktop.

**Comment by usdbrl** [comment]
@SegaSonic2 

Hello again, selenium was upgraded to a new version.
Can you try to upgrade using the command, and see if the error still remains?

pip install selenium --upgrade

**Comment by SegaSonic2** [comment]
It still doesn't work. Gives me yet the same error.

**Comment by usdbrl** [comment]
Well, is this case only @UnMars can try to solve the issue.
Since the update works for some, but doesn't for others, no clue.

Since selenium has a built-in manager, maybe adapt the code and remove "webdriver-manager" library and use selenium instead is the way to go.
