### ISSUE TITLE
Script stuck after the domain change

### ISSUE THREAD

**Issue by hedwig2** [UnMars/Prolific-Joiner#11]
Since Prolific have changed their domain from Prolific.co, to Prolific.com the script now appears to get stuck at the "captcha solved" step. I've let it open for 10+ minutes, but it never goes past that point.

Is there a solution for this?

Thank you :)

<img width="224" alt="image" src="https://github.com/UnMars/Prolific-Joiner/assets/76737462/431564c0-f06d-461c-aab0-ae5ac6354287">

**Comment by usdbrl** [comment]
Open the 'main.py' file and change the URLs that have ".co" to ".com".
You can use your own Windows Notepad and save the changes.

It worked for me. Cheers!

**Comment by UnMars** [comment]
Fixed in the latest commit :p !

**Comment by UnMars** [comment]
Fixed in the latest commit :p !
