### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by n0rmal900** [UnMars/Prolific-Joiner#19]
```
Getting a new bearer token...

DevTools listening on ws://127.0.0.1:3607/devtools/browser/cf51a104-3059-4337-afd5-29ef2dd69e86
Captcha solved in 0.24415802955627441s
```
Since today, it has stopped working and stuck at "Captcha Solved."

**Comment by smithjohn3** [comment]
have the same thing, any idea how to solve it?

**Comment by n0rmal900** [comment]
All I know is that they changed something with logging in because if I turn off the --headless parameter, it automatically logs out after logging in. No idea how to fix it.

**Comment by ndrefg** [comment]
Seems to be a problem with getting the token?

**Comment by SmatMan** [comment]
Yep, same issue. Looking into the request logs, they do not share the token in the same way as before:

```
if request.url.startswith("https://internal-api.prolific.com/openid/authorize?client_id="):
                            new_bearer = request.response.headers['location'].split("&")[0].split("access_token=")[-1]
```

The above url is no longer accessed when logging in, and other URLs do not have a similar access_token field from what I can find. 

In regular api calls in the browser, authorization is done with a Bearer that is much longer, for me 862 characters and separated in seemingly random intervals with periods. Using this token doesn't allow me to authorize however. Looking for another way to authorize but not looking promising at the moment

**Comment by SmatMan** [comment]
Found a fix, working on a pull request!

**Comment by smithjohn3** [comment]
> Found a fix, working on a pull request!

Could You please share what to change in the code?

**Comment by usdbrl** [comment]
@SmatMan and @UnMars 

Can you please check the script using a clean install?
Did on my system, script is still broken.

**Comment by SmatMan** [comment]
> Can you please check the script using a clean install?
> 
> Did on my system, script is still broken.

What doesn't work? What's broken? Please give more details?

**Comment by EnriGrossi** [comment]
In my case,  I have re enabled capcha again ;)

**Comment by usdbrl** [comment]
Sorry, guys, the issue was on my end. 
I've managed to get the latest commit of the script working after a while.
