### ISSUE TITLE
Error 140010

### ISSUE THREAD

**Issue by noekun11** [UnMars/Prolific-Joiner#29]
Im getting the below error for some studies, im worried that my account may be ISP banned, since in the requirements file, 140010 was mentioned as ISP ban or am i getting something wrong here, could you guys please clarify?
thank you @UnMars @conradRz 

"[+] Error code 140010
Title : The data supplied is either incomplete or not valid.
Details : This study is in high demand, please try reserving your submission again"

**Comment by tommyka1** [comment]
This has nothing to do with your account. When the study you're trying to join has a lot of people attempting to join at the same time, this error pops up. This would also occur if you were trying to join the study without using the script.

**Comment by noekun11** [comment]
yes.. thank you, i was able to join a study from the script even after this error code
