### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ShaggyBro** [UnMars/Prolific-Joiner#35]
python .\main.py

> [+] Getting a new bearer token...
> [-] Failed to log in, retrying in 3s...
> [+] Getting a new bearer token...
> [-] Failed to log in, retrying in 3s...
> [+] Getting a new bearer token...
> [-] Failed to log in, retrying in 3s...

Everything was working fine 12h ago, account in good standing and can ping/login with a normal browser.

**Comment by n0rmal900** [comment]
Try this out https://github.com/UnMars/Prolific-Joiner/issues/34#issuecomment-2250304708 it's for windows but very similar.

**Comment by noekun11** [comment]
> That fixed it! Thanks for the troubleshooting @n0rmal900 !

brother... could you please tell me in detail how you fixed... im a bit confused the above

**Comment by noekun11** [comment]
@ShaggyBro @n0rmal900 Thank you soo much... this worked like charm :)

**Comment by hedwig2** [comment]
@n0rmal900 I've tried your solution, but for me it doesn't seem to work as I still have the same issue. Additionally, I've also noticed that once I run the script, the line in the drivers.json is again overwritten with "THIRD_PARTY_NOTICES".

**Comment by ShaggyBro** [comment]
> @n0rmal900 I've tried your solution, but for me it doesn't seem to work as I still have the same issue. Additionally, I've also noticed that once I run the script, the line in the drivers.json is again overwritten with "THIRD_PARTY_NOTICES".

start script,
script hangs on logging in,
stop script,
go to drivers.json,
change to "(...)chromedriver.exe",
propreties > read only,
start script.

next day if it hangs again, remove read only, start script, it changes back to "THIRD_PARTY_NOTICES(...)", change it back to chromedriver.exe, read only again, start script.

Hope it helped cause im doing nothing different than that. (i dont even use read only sometimes)..

**Comment by hedwig2** [comment]
@ShaggyBro Unfortunately this still gives me the same error. Although the name doesn't change anymore, the error persists.
