### ISSUE TITLE
UPDATE REQUIRED

### ISSUE THREAD

**Issue by NoeKun001** [UnMars/Prolific-Joiner#39]
@UnMars @tommyka1 @ShaggyBro
The failed to login is back again.. I tried the method mentioned in #35 initially it solved the problem. but now im getting the same error after the line "Logging In"
I turned the headless mode off (Line 86) and rerun the script... I observed that it is failing to verify captcha and also showing the "https" of auth.profilic.com in red (Means: SSL Crtificate is not Valid) 
Any ways to fix? Please help me out

**Comment by NoeKun001** [comment]
I think the problem is still in the captcha verification.. which giver an Error when i try to verify it... do you guys getting the same error @UnMars @tommyka1 @ShaggyBro

**Comment by NoeKun001** [comment]
> yes sir, my workaround currently was getting the token manually from prolific and start the script with it already inserted.

Brother... could you please tell me how to do it ?
I really really appreciate your help.....

**Comment by NoeKun001** [comment]
> To get your bearer token on chrome based browers: -Go to prolific and login, -Press F12 -Go to the 'Network' Tab -filter by 'internal-api.prolific.com/api/v1/' -click F5 -click on any result and search on the "Request Headers" for something like
> 
> > authorization:
> > Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> -copy it (eg Bearer JABSKJFBGDBGDBSKDBGKBSDGBSDGNB) -parse it (eg paste it into the address bar of your browser and recopy it) -your config.json should look something like this
> 
> > {
> > "auto_renew_bearer" : "True",
> > "pause_on_idle" : "False",
> > "Prolific_ID" : "AAAAAAAAAAAAA",
> > "proxy" : "http://username:password@server:port",
> > "wait_time" : 12
> > }
> 
> -run -paste token
> 
> Notes: if you dont use a proxy just leave it blank `"proxy" : "",` pause on idle is not working, i dont actually use it this is a frankenstein version, expect things to be janky and made in a dumb way guessing the re-entry of the token when it expires wont work as well if idle_pause isnt working, so you will have to close the script and re run it.
> 
> ```
> import platform
> import random
> from argparse import ArgumentParser
> from distutils.util import strtobool
> from json import load
> from pathlib import Path
> from time import sleep, time
> from webbrowser import open_new_tab
> 
> from playsound import playsound
> from requests import Response, get, post
> from requests.structures import CaseInsensitiveDict
> from requests.exceptions import RequestException
> from rich.console import Console
> from rich.text import Text
> 
> if platform.system() == "Windows":
>     import ctypes
> 
> config = load(open(f"{Path(__file__).parent}/config/config.json"))
> 
> class ProlificUpdater:
>     def __init__(self, bearer, proxy=None):
>         self.bearer = bearer
>         self.proxy = proxy
>         self.oldResults = list()
>         self.participantId = config["Prolific_ID"]
>         self.last_ip = None
> 
>     def getRequestFromProlific(self) -> Response:
>         url = "https://internal-api.prolific.com/api/v1/participant/studies/"
>         headers = CaseInsensitiveDict()
>         headers["Accept"] = "application/json, text/plain, */*"
>         headers["Authorization"] = self.bearer
>         headers["x-legacy-auth"] = "false"
>         proxies = {"http": self.proxy, "https": self.proxy} if self.proxy else None
>         try:
>             return get(url, headers=headers, proxies=proxies, timeout=10)
>         except RequestException as e:
>             console.print(f"[bold red]Request error: {e}[/bold red]")
>             return Response()
> 
>     def reservePlace(self, id) -> Response:
>         url = "https://internal-api.prolific.com/api/v1/submissions/reserve/"
>         headers = CaseInsensitiveDict()
>         headers["Accept"] = "application/json"
>         headers["Authorization"] = self.bearer
>         headers["x-legacy-auth"] = "false"
>         postObj = {"study_id": id, "participant_id": self.participantId}
>         proxies = {"http": self.proxy, "https": self.proxy} if self.proxy else None
>         try:
>             return post(url, headers=headers, data=postObj, proxies=proxies)
>         except RequestException as e:
>             console.print(f"[bold red]Request error: {e}[/bold red]")
>             return Response()
> 
>     def getResultsFromProlific(self) -> list:
>         try:
>             response = self.getRequestFromProlific()
>         except Exception:
>             console.print("[bold red][+] Network error[/bold red]")
>             return list()
>         if response.status_code == 200:
>             return response.json()["results"]
>         else:
>             print(f"Response error {response.status_code}")
>             print(f"Response error {response.reason}")
>             return ["bearer"]
> 
>     def executeCycle(self) -> bool:
>         results = self.getResultsFromProlific()
>         if results == ["bearer"]:
>             self.bearer = input("Bearer token not valid anymore, please enter a new bearer token: ")
>             self.bearer = "Bearer " + self.bearer
>             return False
> 
>         print("results : ", results)
>         if results:
>             if results != self.oldResults:
>                 currency_symbol = "£" if str(results[0]["study_reward"]["currency"]) == "GBP" else "$"
>                 console.print(
>                     f"""Trying to join {results[0]["name"]} ([bold green]{currency_symbol}{str(float(results[0]["study_reward"]["amount"])/100)}[/bold green])"""
>                 )
>                 reserve_place_res = self.reservePlace(id=results[0]["id"])
>                 if reserve_place_res.status_code == 400:
>                     console.print(f"""[bold red][+] Error code {str(reserve_place_res.json()["error"]["error_code"])}
>                                       \nTitle : {str(reserve_place_res.json()["error"]["title"])}
>                                       \nDetails : {str(reserve_place_res.json()["error"]["detail"])}""")
>                     self.oldResults = results
>                     return False
>                 else:
>                     a_website = "https://app.prolific.com/studies"
>                     open_new_tab(a_website)
>                     playsound(rf"{Path(__file__).parent}\alert.wav", True)
> 
>         self.oldResults = results
> 
>         if results:
>             return True
>         else:
>             return False
> 
>     def check_ip(self) -> str:
>         ip_services = [
>             'https://api.ipify.org?format=json',
>             'https://api.my-ip.io/ip.json',
>             'https://checkip.amazonaws.com',
>             'https://api.ipstack.com/check?access_key=YOUR_ACCESS_KEY'
>         ]
>         for service in ip_services:
>             try:
>                 response = get(service, proxies={"http": self.proxy, "https": self.proxy} if self.proxy else None)
>                 if response.status_code == 200:
>                     return response.json().get("ip", response.text.strip())
>             except RequestException:
>                 continue
>         return "Unable to get IP"
> 
> def parseArgs() -> dict:
>     parser = ArgumentParser(description="Keep updated with Prolific")
>     parser.add_argument("-b", "--bearer", type=str, help="bearer token")
>     args = parser.parse_args()
>     bearer = "Bearer " + args.bearer if args.bearer else None
>     return {"bearer": bearer}
> 
> if platform.system() == "Windows":
> 
>     class LASTINPUTINFO(ctypes.Structure):
>         _fields_ = [("cbSize", ctypes.c_uint), ("dwTime", ctypes.c_uint)]
> 
>     def get_idle_duration():
>         lii = LASTINPUTINFO()
>         lii.cbSize = ctypes.sizeof(LASTINPUTINFO)
>         if ctypes.windll.user32.GetLastInputInfo(ctypes.byref(lii)):
>             millis = ctypes.windll.kernel32.GetTickCount() - lii.dwTime
>             seconds = millis / 1000
>             return seconds
>         else:
>             error_code = (
>                 ctypes.windll.kernel32.GetLastError()
>             )  # Get the last error code
>             print(f"Error code: {error_code}")
>             return 0  # Handle the error as needed
> 
>     def pause_script():
>         print("Pausing script...")
>         while True:
>             idle_duration = get_idle_duration()
>             if idle_duration > 600:  # 10 minutes in seconds
>                 print(
>                     f"Idle Time: {idle_duration} seconds [script paused after 10 minutes of inactivity, to avoid temp ban from the API due to overuse]"
>                 )
>                 sleep(10)
>             else:
>                 print("Resuming script...")
>                 break
> 
> if __name__ == "__main__":
>     myArguments = parseArgs()
>     bearer = myArguments.get("bearer") or input("Please enter your bearer token: ")
>     bearer = "Bearer " + bearer
>     proxy = config.get("proxy")
>     p_updater = ProlificUpdater(bearer=bearer, proxy=proxy)
> 
>     # Initial IP check
>     ip_address = p_updater.check_ip()
>     if ip_address == "Unable to get IP":
>         console = Console()
>         console.print(f"[bold red]Unable to get IP from all services. Stopping script.[/bold red]")
>         exit()
> 
>     p_updater.last_ip = ip_address
>     console = Console()
>     console.print(f"Current IP address: {ip_address}")
> 
>     status = console.status("[bold blue] Waiting for study...", spinner="arc")
>     status.start()
> 
>     # Initial sleep
>     sleep(5)
> 
>     while True:
>         updateTime = config["wait_time"]
>         if p_updater.executeCycle():
>             status.stop()
>             text = Text("Study found !")
>             text.stylize("bold red")
>             console.print(text)
>             sleep(5)
>             input("Press enter to resume study search")
>             status.start()
> 
>         if strtobool(config["pause_on_idle"]) and platform.system() == "Windows":
>             idle_duration = get_idle_duration()
>             if idle_duration >= 600:  # 10 minutes in seconds
>                 pause_script()
>             # else:
>             #     print(f"Idle Time: {idle_duration} seconds [script not paused]") #leave commented if not debugging
> 
>         # IP check every 2 minutes
>         current_ip = p_updater.check_ip()
>         if current_ip != p_updater.last_ip:
>             console.print(f"[bold red]IP address has changed from {p_updater.last_ip} to {current_ip}. Stopping script.[/bold red]")
>             exit()
> 
>         # Generate a random integer between -5 and 5
>         random_offset = random.randint(-1, 3)
> 
>         # Generate a random number which is +/- 5 from the updateTime variable
>         random_time = updateTime + random_offset
>         sleep(
>             random_time if random_time >= 0 else 0
>         )  # if statement covers edge case, if the user sets up <5 wait_time (I found <20 results in a temp ban), which with the use of random above, could result in a negative number being passed to the sleep()
> ```

Brother you are my greatest savious... I pay homage to you!
Just a doubt... when will i have to change the bearer token though? (is there any general interval of time?) and suppose if the token expires while the script is running.... does it indicate me to enter other bearer token or just simply stops?
Thank yuo bro

**Comment by NoeKun001** [comment]
@ShaggyBro Brother i think, the previous script is not working because of prolific team... look [here](https://www.reddit.com/r/ProlificAc/comments/1eml7iu/interesting_comment_from_someone_using_a_prolific/?sort=new) It seems someone reported you and also the support team said to took action.... it would be better if you delete the above method from github as well or i think now that we are on rador of prolific. they might again come up with some other ways to block the script access...(btw its your decision to delete or not... I just wanted you to alert about the reddit users) and additionally... is there a way i can keep in touch with you (except for github)
Thanks

**Comment by amitader** [comment]
![image](https://github.com/user-attachments/assets/bb78c6bd-0fbe-4db2-8b91-c4506d4d7765)
After about 2 minutes it returns an error, is there a way to solve it other than giving it a new token every time?

**Comment by amitader** [comment]
Maybe add that there will be a sound when the script stops because of an error

**Comment by profbiyi** [comment]
@ShaggyBro is it not possible to just put the token generated in the code? i did that and the script never told me that my token is not valid again...

**Comment by profbiyi** [comment]
> > @ShaggyBro is it not possible to just put the token generated in the code? i did that and the script never told me that my token is not valid again...
> 
> yes it should work untill it is invalid and ask for another/close the script

so i placed in in those two places and it never tells that its not valid, i will monitor it and get to know if i am missing something. thanks for all your help brotherly
<img width="830" alt="Screenshot 2024-08-18 at 14 22 47" src="https://github.com/user-attachments/assets/199a4937-1e7a-4c67-af13-600fed02aaec">
<img width="928" alt="Screenshot 2024-08-18 at 14 22 11" src="https://github.com/user-attachments/assets/a79913e3-661f-4423-b080-f36fd1dadd76">

**Comment by notquitemoe** [comment]
Yeah I wonder if they changed stuff again, or is it a temporary error. Help would be nice.

**Comment by ThisIsNotUdyr** [comment]
Did anyone find a solution for the PEC-SUB-0010 error?

**Comment by SoolaimanG** [comment]
Please have anyone encounter PEC-SUB-0011?

**Comment by n0rmal900** [comment]
As Far I can tell they changed captcha to Turnstile (Cloudflare), it can be bypassed by SeleniumBase UC Mode quite easily, however not sure if this solve PEC=SUB-0010.

**Comment by profbiyi** [comment]
@ShaggyBro @UnMars any update please?

**Comment by Arslan30** [comment]
Error returns that the information is incomplete. I guess prolific changed their API so that it requires something more than a prolific ID to join a study. Someone will have to read documentation and figure out what it is. It failed me on multiple studies and was never able to join since this change happened
