### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by hedwig2** [UnMars/Prolific-Joiner#4]
Up until 2 days ago this script has been working flawlessly. However yesterday I've started to notice the script doesn't autojoin surveys anymore. I've realized this when I received a notification for a follow up survey (so I can be 100% sure I was eligible and there were spaces still available) from the official prolific assistant, however this script had done nothing.
This script has really been game changing for me and hopefully there is something that can be done to fix this! 
Thank you so much to the developer in advance :)

**Comment by usdbrl** [comment]
I'm also having the same problem recently. The official extension notifies me, but the script doens't join any study.

**Comment by hedwig2** [comment]
I'm so sorry to hear you're experiencing this issue as well. Hopefully it's nothing big and requires just a minor fix.
