### ISSUE TITLE
Error running the scipt

### ISSUE THREAD

**Issue by hedwig2** [UnMars/Prolific-Joiner#6]
After the new update, trying to run the script returns this error:
![1](https://github.com/UnMars/Prolific-Joiner/assets/76737462/686719e0-69f8-4a26-b1eb-1f32bd78df8f)

**Comment by UnMars** [comment]
Did you updated all the files ? (There's a new parameter wait_time in the config.json file to change easily the time the program waits between each study check)

**Comment by usdbrl** [comment]
I believe the script tries to retrieve information of "wait_time" from the config.json file. But the script itself is unable to create this parameter inside the file. So, I think the parameter needs to be placed manually (I believe you didn't update the config.json on GitHub).

All things considered, I can also be wrong. That's just my two cents.

**Comment by hedwig2** [comment]
I did a clean install of the new version.

**Comment by UnMars** [comment]
Ok that's on me I forgot to commit the changes for the config.json file. 
Everything should be working now ! :)

**Comment by hedwig2** [comment]
Thanks for the quick updates!😃
