### ISSUE TITLE
Error with alert.wav file

### ISSUE THREAD

**Issue by hedwig2** [UnMars/Prolific-Joiner#7]
Lately, whenever I'm using the script on my laptop, I've been getting this error with the "alert.wav" file. The script doesn't play the alert sound, however it does join the study. Weirdly, the script works without any errors like this on my desktop.
![1](https://github.com/UnMars/Prolific-Joiner/assets/76737462/c3c61f5d-1b54-4ba0-803e-77bd8a9ca3fb)

**Comment by Kebab81** [comment]
I also sometimes get this error. I noticed that when playing League Of Legends, the program can throw an error like in the screenshot above.

**Comment by hedwig2** [comment]
That's interesting. I do have League installed, however it's not running in the background at the time of getting this error. I'll try to uninstall it for now, and see if the issue persists.

**Comment by conradRz** [comment]
I just went with 

`from winsound import PlaySound, SND_FILENAME`

as opposed to the original

`from playsound import playsound`

as I had a similar error, but constantly. 

I don't want to pull request that, as it would stop the script from being cross platform (think of Mac/Linux users)

**Comment by hedwig2** [comment]
@conradRz If I understand correctly, you just replaced this line in the code `from playsound import playsound` with `from winsound import PlaySound, SND_FILENAME` and it has fixed this problem entirely?

**Comment by conradRz** [comment]
I used a form of "thought shortcut", because of certain assumptions I had made.

in the terminal hit
`pip3 install winsound`

also replace 
`playsound(fr'{Path(__file__).parent}\alert.wav', True)`
with 
`PlaySound('alert.wav', SND_FILENAME)`

**Comment by hedwig2** [comment]
@conradRz Thank you so much! This finally fixed it for me.
